### ISSUE TITLE
Wezterm Modus Operandi has bright colors

### ISSUE THREAD

**Issue by TimoKramer** [miikanissi/modus-themes.nvim#10]
### Description

Hi, thanks for this great nvim theme. I tried your wezterm colors as well but they look too bright, modus is quite decent (like your nvim colors). Comparing it to [ishan9299](https://github.com/ishan9299/modus-theme-vim) your wezterm colors look quite a bit brighter and I find both modus themes are quite far from the nvim colors. 
In the screenshot you can see left the ishan-theme right yours and on the bottom is github-light.
![image](https://github.com/miikanissi/modus-themes.nvim/assets/4785848/fa1c2f55-ae01-449e-9680-7854b7870f88)

### Neovim version

```markdown
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1702233742
```

### Terminal and multiplexer

wezterm 20240203-110809-5046fc22

### Modus themes version

master

### Steps to reproduce

Install wezterm and add the color scheme:
```
color_scheme_dirs = join(home, ".config", "wezterm", "colors")
color_scheme = 'Modus Operandi',
```

### Repro

```Lua
not nvim related
```

**Comment by miikanissi** [comment]
Hey,

The wezterm colors are generated [here](https://github.com/miikanissi/modus-themes.nvim/blob/master/lua/modus-themes/extras/wezterm.lua) from the base modus-themes colors from [here](https://github.com/miikanissi/modus-themes.nvim/blob/master/lua/modus-themes/colors.lua).

So the 16 color terminal values are the same as used in the theme and I don't see an issue with them in the example. Looks correct to me.
