### ISSUE TITLE
Telescope prompt has a red and grey border

### ISSUE THREAD

**Issue by tjkuson** [miikanissi/modus-themes.nvim#19]
### Description

I just updated the plugin and now the Telescope search prompt has a strange-border around it. It doesn't look intentional, and I think it looks worse than it was before.

Before the update:

<img width="2032" alt="Screenshot 2024-05-21 at 21 56 04" src="https://github.com/miikanissi/modus-themes.nvim/assets/12143269/7b3c2145-a808-4b3e-8557-852b029549f7">

After the update:

<img width="2032" alt="Screenshot 2024-05-21 at 21 56 11" src="https://github.com/miikanissi/modus-themes.nvim/assets/12143269/c91026ed-3caf-4af5-ad17-4599b8d13164">

There were also changes to `class`, `from` and `import` keywords that weren't documented, but they might be intentional.

PS: Thank you for your maintenance of the project and the new update! I especially like the italic docstrings.

### Neovim version

```markdown
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1713773202
```

### Terminal and multiplexer

iTerm2 3.5.0

### Modus themes version

modus-themes.nvim 1.2.0

### Steps to reproduce

1. `nvim -u repro.lua`
2. `:Telescope`
3. Observe the Telescope prompt

<img width="777" alt="Screenshot 2024-05-21 at 22 04 38" src="https://github.com/miikanissi/modus-themes.nvim/assets/12143269/36afc011-a367-457a-a67f-dd4a626a3157">

### Repro

```Lua
local root = vim.fn.fnamemodify("./.repro", ":p")

for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

local plugins = {
  "miikanissi/modus-themes.nvim",
  { "nvim-telescope/telescope.nvim", dependencies = { "nvim-lua/plenary.nvim" } },
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("modus")
```

**Comment by miikanissi** [comment]
Hi, thanks for the detailed report!

The change to highlight the active floating border is intentional, but it is supposed to be subtle. I think it should only highlight the actual border (foreground) and the background should remain the same as before. I will correct that. 

And yes there were intentional changes made to the `import`, `from`, `class` highlight groups. This was mostly the result of the old version not having these correctly configured for treesitter v0.9.2 in the first place. I need to do a better job at documenting these changes.

**Comment by tjkuson** [comment]
Thank you! And no worries about documenting the `import`, `from`, and `class` keywords. I brought them up only because they were visible in the screenshot, and I wasn't certain if they were unintentional. I wouldn't have raised it if not for the Telescope border.
