### ISSUE TITLE
Adjust highlight groups for better readability?

### ISSUE THREAD

**Issue by SwordOfMyBone** [miikanissi/modus-themes.nvim#2]
Right now treesitter highlights everything with color in c++. For example, "ifndef" is completely highlighted in red (because both "PreProc" and "Macro" link to the same color), whereas in the screenshot below with the modus theme there is white text (also for number literals).

https://emacs.amodernist.com/static/images/modus-vivendi.svg

Sometimes it is tough to distinguish between color coded elements because there are a lot of clashes (eg: class is purple, function is purple, and operators are purple) between highlight groups. 

Is there a way to adjust this? If you would like me to fix this I wouldn't mind attempting, but I'm not very familiar with treesitter so it might take a while.

**Comment by miikanissi** [comment]
Thanks for bringing this to my attention. It is true that a lot of the treesitter highlight groups are using the same colors. This was mostly an oversight as I did not spend a ton of time fine tuning things. I will be taking a closer look at the treesitter highlights and try to mimic the original Emacs highlighting as much as possible.

**Comment by miikanissi** [comment]
On another note. If you'd like to customize the highlight groups for your personal use, you can override them in the configuration. For example to override the PreProc highlight group from the default `red_cooler` to `blue_cooler` you can do this. Optionally you can define your own color in hex:

```lua
{
    "miikanissi/modus-themes.nvim",
    priority = 1000,
    config = function()
        require("modus-themes").setup({
            on_highlights = function(hl, c)
                hl.PreProc = { fg = c.blue_cooler }
                hl.Include = { fg = "#550000" }
            end,
        })
        vim.cmd([[colorscheme modus]])
    end,
},
```

To find all the available colors you can refer to: https://github.com/miikanissi/modus-themes.nvim/blob/master/lua/modus-themes/colors.lua

And for finding different hightlight groups refer to:
https://github.com/miikanissi/modus-themes.nvim/blob/master/lua/modus-themes/theme.lua
