### ISSUE TITLE
Very overpowering inlay hints

### ISSUE THREAD

**Issue by 0xricksanchez** [miikanissi/modus-themes.nvim#23]
### Description

Hi,
firstly great theme! I just added this to [AstroNvim](https://github.com/AstroNvim/astrocommunity/commit/7ad964c061c25be065ceebc99e52b5ad632b6af2) for everybody to try!
I'm encountering a small problem regarding inlay hints:

![image](https://github.com/miikanissi/modus-themes.nvim/assets/17012133/32e6839b-4ebf-4857-863f-6e019e1f21bd)

IMHO the inlay hints are too overpowering (compare the big bold teal boxes), and they should be more subtle as they're only an additional/optional source of information. Currently, it looks like they're the main source of information that I absolutely have to look at.

### Neovim version

```markdown
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1713773202
```

### Terminal and multiplexer

kitty 0.34.1 

### Modus themes version

v1.2.1

### Steps to reproduce

Just set the `modus_vivendi` them on any rust code for example :)

**Comment by miikanissi** [comment]
Hi and thanks a lot for adding it there!

That indeed looks terrible, thanks for raising the issue. Haven't noticed before as I don't personally use inlay hints. 

I will be changing it to use the same highlights as comments do. This way it will be subtle, yet clear that it is not "real" text.

**Comment by 0xricksanchez** [comment]
Looks great now! Thanks, much appreciated

**Comment by madjxatw** [comment]
Thanks for the fix!
