### ISSUE TITLE
Foreground color for candidates matched by motion plugins

### ISSUE THREAD

**Issue by madjxatw** [miikanissi/modus-themes.nvim#28]
### Description

I'm using [flash.nvim](https://github.com/folke/flash.nvim) for easy motion, but the foreground color for matched candidates are bit of invisible, see the screenshot below.

![screenshot_20240917-070057UTC](https://github.com/user-attachments/assets/ec5d5fe2-b5ee-41c0-9b93-ab520470ec19)

Any advice for a fix?

### Neovim version

```markdown
NVIM v0.10.1
Build type: RelWithDebInfo
LuaJIT 2.1.1720049189
```

### Terminal and multiplexer

kitty 0.36.1

### Modus themes version

master branch `f978043`

### Steps to reproduce

1. Install `flash.nvim` and do a search.
2. Check the background color and foreground color on each matched candidate.

**Comment by miikanissi** [comment]
Thanks for raising the issue. This was an issue with the incorrect background color value being used. Fixed in the latest version.

**Comment by madjxatw** [comment]
Thanks for the quick fix!
