### ISSUE TITLE
Can't produce `extras` locally

### ISSUE THREAD

**Issue by azzamsa** [miikanissi/modus-themes.nvim#37]
I wanted to add `yazi` theme #36 

But `nvim --headless "+lua require('modus-themes.extras').setup()" +qa` did nothing. Am I missing something?

Thanks for `modus port` 🥞

**Comment by miikanissi** [comment]
Hi thanks for the PRs! 

In order for that command to work with your own changes you need to use the local version of the plugin in your nvim config using the `dir` config option. 

Example here:
```lua
	{
		-- "miikanissi/modus-themes.nvim", -- Modus themes
		dir = "~/Documents/modus-themes.nvim",
		priority = 1000,
		config = function()
			require("modus-themes").setup({
				hide_inactive_statusline = true,
			})
			vim.cmd.colorscheme("modus")
		end,
	},
```

**Comment by azzamsa** [comment]
We should include this in the contributing section, I will make a PR.

**Comment by miikanissi** [comment]
Changed the way the extras are built in #39 . It does not rely on your own nvim config anymore and instead uses a minimal config to build.
