### ISSUE TITLE
Add option to disable dimming inactive buffers

### ISSUE THREAD

**Issue by fingolfin19** [miikanissi/modus-themes.nvim#4]
I think nvim ports of Modus themes started dimming NormalNC highlight because early versions of Modus themes supported Solaire-mode, the emacs package for dimming non-text buffers, however:

- Solaire mode does not dim inactive buffers at all, it dims non-text buffers like terminals and file explorer drawers
- Modus themes removed support for Solaire mode ([reasons here](https://gitlab.com/protesilaos/modus-themes/-/blob/main/CHANGELOG.org#L2009))

So it would be nice to have an option to disable dimming inactive buffers to more closely mimic Modus Themes' behavior (I'd argue that not dimming should be the default)

Workaround I could use instead would be 

```lua
 on_highlights = function(hl, c)
                hl.NormalNC = { bg = "#FFFFFF" }
            end,
```

**Comment by miikanissi** [comment]
Hey, thanks for raising an issue. I think you make a fair point. The reason for dimming inactive buffers was mainly a personal preference of mine, but as the goal of this project is to stay true to the original, I will be correcting that. 

I might keep the "solaire mode" as an option to toggle.
