### ISSUE TITLE
Zellij highlight is not visible

### ISSUE THREAD

**Issue by azzamsa** [miikanissi/modus-themes.nvim#40]
### Description

```diff
-       bg "${bg_dim}"
+      bg "${bg_main}"
```

Context: https://github.com/miikanissi/modus-themes.nvim/commit/5242feb6b3aff8823be1d0d614b6dcec3089f7e2

When you set Zellij's `bg` to match the terminal background, the cursor or keyboard highlight becomes invisible. That's why it always uses a color that's different from the background or the `black` value.

Below, I set `bg` to `border = "#646464"` to make a point. If you set `bg` to `$bg_main`, it will be completely invisible.

![image](https://github.com/user-attachments/assets/a32e34e6-dafc-45e2-89df-ae1b2e7d3ae5)

### Neovim version

```markdown
NVIM v0.10.2
Build type: Release
LuaJIT 2.1.1713484068
```

### Modus themes version

a702bfb

### Steps to reproduce

1. `cp extras/zellij/modus_vivendi.kdl  ~/zellij/themes/modus_vivendi.kdl`

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "miikanissi/modus-themes.nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("modus")
-- add anything else here
```

**Comment by miikanissi** [comment]
Thank you for raising the issue. I wasn't quite sure why the bg value was different in the original PR, but this makes sense. Fixed in #42 by setting the bg value to the line highlight value.

**Comment by azzamsa** [comment]
Should we add a comment above `bg` to prevent any confusion down the line?

**Comment by miikanissi** [comment]
Good idea! Added.
