### ISSUE TITLE
Bad contrast selected item completion menu

### ISSUE THREAD

**Issue by louwers** [miikanissi/modus-themes.nvim#44]
The difference between the selected item and the non-selected item is minimal.

<img width="527" alt="image" src="https://github.com/user-attachments/assets/d8694f8c-cd66-4d75-a8aa-0f67899f0394">

Also in other dark themes, the selected item is lighter instead of darker.

For comparison:

<img width="765" alt="image" src="https://github.com/user-attachments/assets/60d227f4-2a95-4df7-9899-ff95690bc6d5">

<img width="736" alt="image" src="https://github.com/user-attachments/assets/f25e630c-ab3e-434a-9562-752726f5547a">

<img width="746" alt="image" src="https://github.com/user-attachments/assets/dc95c14b-1290-4ddc-9c91-d05338e7a11e">

<img width="773" alt="image" src="https://github.com/user-attachments/assets/60fbd4a9-60ff-4b19-9d0e-909d1618af54">

<img width="763" alt="image" src="https://github.com/user-attachments/assets/25bfd99e-18f7-4657-a8c6-6b24c6140613">

Of these, I think with Modus it's the hardest to see the selected option with Modus by far.

**Comment by miikanissi** [comment]
Thank you for raising the issue. This is now fixed in the latest release. The background and foreground are inverted.

**Comment by louwers** [comment]
Wow awesome!
