### ISSUE TITLE
Add option to enable transparency

### ISSUE THREAD

**Issue by vihu** [miikanissi/modus-themes.nvim#5]
### Description

Hello, would you be open to add an option (just like dim_inactive) to allow users to enable transparency (as supported by the terminal)?

Thanks!

### Additional context

For example, here's how [gruvbox](https://github.com/ellisonleao/gruvbox.nvim/blob/main/lua/gruvbox.lua#L288), [kanagawa](https://github.com/rebelot/kanagawa.nvim/blob/master/lua/kanagawa/highlights/editor.lua#L77) and [bamboo](https://github.com/ribru17/bamboo.nvim/blob/master/lua/bamboo/highlights.lua#L65) do it. Personally I prefer the approach taken by bamboo since it works very well alongside dim_inactive and other plugins (including nvim-tree).

**Comment by miikanissi** [comment]
Hey, thanks for the request! I can definitely add that as an option.
