### ISSUE TITLE
Do you plan to create a port for `protesilaos/ef-themes` ?

### ISSUE THREAD

**Issue by azzamsa** [miikanissi/modus-themes.nvim#51]
### Description

```markdown
Hi.

I like this port of `modus`. Do you have any plan to port `protesilaos/ef-themes` ?
```

### Additional context

I like `modus` but to me, it looks like I am in 90'.

**Comment by miikanissi** [comment]
Hi, I don't have plans to port them at the moment. I really like the themes but there are so many variants that maintaining it would become a lot of work.

**Comment by azzamsa** [comment]
> themes but there are so many variants that maintaining it would become a lot of work.

Yeah, I am thinking the same. :)
