### ISSUE TITLE
Text in Markdown headings invisible with headlines.nvim plugin

### ISSUE THREAD

**Issue by madjxatw** [miikanissi/modus-themes.nvim#7]
### Description

When using  [ lukas-reineke/headlines.nvim"](https://github.com/lukas-reineke/headlines.nvim), Markdown headings are not highlighted properly with modus light theme. The pic below shows how heading 1, 2 and 3 are rendered.  It seems some other themes have this kind of issue too, as my test result, the catppuccin theme works well with `headlines.nvim`.

![screenshot_20240101-160448UTC](https://github.com/miikanissi/modus-themes.nvim/assets/6035833/283e8d98-fb68-4bd6-b311-6ccf35782033)

### Neovim version

```markdown
NVIM v0.9.4
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Terminal and multiplexer

kitty 0.29.2

### Modus themes version

modus-themes.nvim v1.1.1

### Steps to reproduce

1. Set style to `modus_operandi`
2. Activate `modus` theme

### Repro

Settings for `modus-themes.nvim`:

```lua
  {
    "miikanissi/modus-themes.nvim",
    priority = 1000,
    opts = {
      style = "modus_operandi",
      variant = "deuteranopia", -- tinted, deuteranopia, tritanopia
      -- dim_inactive = true,
    },
  },
```

Settings for `headlines.nvim`:

```lua
  {
    "lukas-reineke/headlines.nvim",
    enabled = false,
    opts = function()
      local opts = {}
      for _, ft in ipairs({ "markdown", "norg", "rmd", "org" }) do
        opts[ft] = {
          headline_highlights = {},
        }
        for i = 1, 6 do
          local hl = "Headline" .. i
          vim.api.nvim_set_hl(0, hl, { link = "Headline", default = true })
          table.insert(opts[ft].headline_highlights, hl)
        end
      end
      return opts
    end,
    ft = { "markdown", "norg", "rmd", "org" },
    config = function(_, opts)
      vim.schedule(function()
        require("headlines").setup(opts)
        require("headlines").refresh()
      end)
    end,
  },
```

**Comment by miikanissi** [comment]
Thanks for reporting the issue. It was an oversight in the highlight groups which set the foreground and background as the same value. I have now corrected this.

**Comment by madjxatw** [comment]
Thanks for the quick fix!
