### ISSUE TITLE
Marks in gutter have a different background

### ISSUE THREAD

**Issue by shartf** [miikanissi/modus-themes.nvim#8]
### Description

When I create marks they have a distinctive background around them.
<img width="485" alt="Screenshot 2024-01-15 at 10 00 42" src="https://github.com/miikanissi/modus-themes.nvim/assets/10035382/4ca2d2bf-d060-47d8-9ddc-f26cf4813f5d">
Not sure if it is a bug, it may be related to some settings in LazyVim which I am using. I've noticed that in theme screenshot in the reprositary marks and git status are in the same line. On the other side, I've not seen such behavior in any other theme I've used.

**UPDATE**: Ok, I cannot see such behavior in WezTerm, it seems to be iTerm-related.
<img width="372" alt="Screenshot 2024-01-15 at 10 28 21" src="https://github.com/miikanissi/modus-themes.nvim/assets/10035382/e86c259b-aaf7-4f04-a490-1913c3f01465">
But WezTerm does not show line numbers and git gutter having a separate background at all, other than if selected. I am confused. Can the separate background for line numbers and marks be switched off, completely?

### Neovim version

```markdown
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1703358377
```

### Terminal and multiplexer

iTerm2 3.5.0beta18

### Modus themes version

modus-themes.nvim v1.1.1

### Steps to reproduce

Open any file and set a mark

**Comment by miikanissi** [comment]
Hey, I wasn't able to reproduce this issue with my configuration. Are you able to provide a repro.lua file which reproduces this error?

```lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
	"miikanissi/modus-themes.nvim",
	-- add any other plugins here
}
require("lazy").setup(plugins, {
	root = root .. "/plugins",
})

vim.cmd.colorscheme("modus")
-- add anything else here
```

Save this as repro.lua and run with nvim -u repro.lua

**Comment by shartf** [comment]
Hi, 

keep the issue open for a while, I will try to port parts of LazyVim config to a repro.lua and reproduce the problem, may need some time.

**Comment by shartf** [comment]
I believe it is this function: https://github.com/LazyVim/LazyVim/blob/879e29504d43e9f178d967ecc34d482f902e5a91/lua/lazyvim/util/ui.lua#L55-L63 , called by https://github.com/LazyVim/LazyVim/blob/879e29504d43e9f178d967ecc34d482f902e5a91/lua/lazyvim/util/ui.lua#L94-L140 to show marks in the gutter, but my lua skills are not sufficient to apply it a barebone config so far...

**Comment by shartf** [comment]
I've tried it with https://github.com/chentoast/marks.nvim and there I cannot observe the issue. Whatever it is, it is something very specific between custom code of folke, this theme and hl of signs. It looks like a very tedious task to debug it, so that I better close it. :) Thanks for your time!
