### ISSUE TITLE
kitty bold black contrast

### ISSUE THREAD

**Issue by adamcstephens** [miikanissi/modus-themes.nvim#9]
### Description

Hi, thanks for the awesome project. I've replaced some of my own ports with your generated ones.

Unfortunately, I find the default bold black, `color8 #1e1e1e` to lack sufficient contrast in some cases. Here are a couple examples which don't look awful at large size, but when regular screen size are quite hard to see.

### senpai

![image](https://github.com/miikanissi/modus-themes.nvim/assets/2071575/2529aecb-8410-4e95-bf69-795fc716d061)

### btop

multiple items, including text for changing options

![image](https://github.com/miikanissi/modus-themes.nvim/assets/2071575/061f4088-72a1-4346-8093-8c226ced2e72)

I could patch this color myself, but I'm wondering if maybe you'd be interested in picking a lighter grey? 

### Neovim version

```markdown
not neovim related :)
```

### Terminal and multiplexer

kitty 0.31.0

### Modus themes version

v1.1.1

### Steps to reproduce

load modus-vivendi in kitty, open btop or senpai.

**Comment by miikanissi** [comment]
The color8 is a bright variant of color0 which is black (or white in light theme). It shouldn't be used as a foreground color. This seems to be an issue with btop or btop theming.

**Comment by adamcstephens** [comment]
That's two examples, and I could probably find more if I switched back to your default. It may be unfortunate that application developers are using it for foreground, but they are and the default makes them unusable at times.
